# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09c34814fd7c15ffec5ad45ffe886e2f0c9146b1f5b8aa03df328bae470d5fdf8d28717bcb3896097cbf42586c585af3a55176198fbf12ec2ba230044754000e

test:
  secret_key_base: d676f85ffe99a33ee1a8867076ef969322bd2a51e10868d5ddb7a8e677c4c19d0dd16ca0125e87326776566001c23920dd74a0203b378760ae6f13c82aa94c86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
